small_model:
  name: qwen2.5vl:3b
  # ollama_server: http://localhost:11434
  ollama_server: http://10.41.74.178:11434
  # engine: ollama  # (default) options: ollama, openai
large_model:
  # engine: ollama
  # name: qwen2.5vl:7b
  # ollama_server: http://10.41.74.178:11434

  # ollama_server: http://localhost:11434
  # name: gpt-4o  # Use OpenAI GPT-4o (vision)
  name: gpt-4o-mini  # Use OpenAI GPT-4o (vision)
  engine: openai  # options: openai, ollama
  # If engine: openai, the OpenAI API key must be set in the environment or .env file
  batch_inference:
    enabled: true           # Enable batch mode for large inference (OpenAI only)
    batch_size: 4           # Number of images to send in a batch
    min_time_diff_seconds: 0.5 # Minimum time difference between images in the batch

server_ips:
  backend: "http://localhost:8000"  # The address where the FastAPI backend service is running
  gradio: "http://localhost:7860"   # The address where the Gradio UI service is running
default_triggers:
  - "a person lying on the floor"
rtsp_cameras:
  # - name: "Desk Camera"
  #   address: "rtsp://192.168.68.110/axis-media/media.amp"
  #   username: "root"
  #   password: "hailo"
  - name: "Office Camera"
    address: "rtsp://192.168.241.62/axis-media/media.amp"
    username: "root"
    password: "hailo"

# --- Debugging ---

debug_save_frames: true