small_model:
  name: qwen2.5vl:3b
  ollama_server: http://localhost:11434
large_model:
  # name: qwen2.5vl:3b
  # ollama_server: http://localhost:11434
  name: qwen2.5vl:7b
  ollama_server: http://10.41.74.178:11434
server_ips:
  backend: "http://localhost:8000"
  gradio: "http://localhost:7860"
default_triggers:
  - "a person falling down"
  - "a blue car"
  - "a test pattern"
rtsp_cameras:
  # - name: "Desk Camera"
  #   address: "rtsp://192.168.68.110/axis-media/media.amp"
  #   username: "root"
  #   password: "hailo"
  - name: "Office Camera"
    address: "rtsp://192.168.241.62/axis-media/media.amp"
    username: "root"
    password: "hailo"

